#!/usr/bin/env bash
# Install claude-statusline into ~/.claude and wire it into settings.json.
#
#   ./install.sh              a shim in ~/.claude that runs this checkout (fastest; updates with git pull)
#   ./install.sh --copy       a standalone copy instead (portable; no checkout needed afterwards)
#   ./install.sh --symlink    a symlink instead of a shim
#   ./install.sh --quest      also switch Claude Quest on (hooks, /quest, the quest line)
#   ./install.sh --no-config  do not create a config file
#   ./install.sh --uninstall  put back the status line you had before
#
# Safe to re-run. Anything it replaces is backed up to <file>.bak-<timestamp>.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
TARGET="$CLAUDE_DIR/statusline.py"
PKG_TARGET="$CLAUDE_DIR/claude_statusline"
SETTINGS="$CLAUDE_DIR/settings.json"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/claude-statusline"
CONFIG="$CONFIG_DIR/config.toml"
BIN="$HOME/.local/bin"
STAMP="$(date +%Y%m%d-%H%M%S)"

MODE=shim
SEED_CONFIG=1
UNINSTALL=0
QUEST=0
for arg in "$@"; do
  case "$arg" in
    --copy)      MODE=copy ;;
    --symlink)   MODE=symlink ;;
    --quest)     QUEST=1 ;;
    --no-config) SEED_CONFIG=0 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help)   sed -n '2,11p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

say() { printf '  %s\n' "$*"; }

SHIM_MARK="Generated by claude-statusline/install.sh"
ENTRY_MARK="The engine lives in the claude_statusline package"

is_ours() { grep -q -e "$SHIM_MARK" -e "$ENTRY_MARK" "$1" 2>/dev/null; }
is_our_pkg() { grep -q "claude-statusline" "$1/__init__.py" 2>/dev/null; }

backup() {
  local f="$1" dest n
  [ -e "$f" ] || return 0
  [ -L "$f" ] && return 0
  # Never back up a file we generated: repeated installs would bury the
  # user's real file under copies of our own shim.
  is_ours "$f" && return 0
  dest="$f.bak-$STAMP"; n=1
  while [ -e "$dest" ]; do dest="$f.bak-$STAMP-$n"; n=$((n + 1)); done
  cp -p "$f" "$dest"
  say "backed up $(basename "$f") -> $(basename "$dest")"
}

link_bin() {
  local name="$1"
  mkdir -p "$BIN" 2>/dev/null || return 0
  if [ -L "$BIN/$name" ] || [ ! -e "$BIN/$name" ]; then
    ln -sfn "$TARGET" "$BIN/$name"
    say "linked $BIN/$name"
  fi
}

if [ "$UNINSTALL" -eq 1 ]; then
  echo "Uninstalling claude-statusline..."
  if [ -f "$TARGET" ] && grep -q "quest hook" "$SETTINGS" 2>/dev/null; then
    python3 -S "$TARGET" quest disable >/dev/null 2>&1 && say "switched Claude Quest off (your save is kept)" || true
  fi
  if [ -L "$TARGET" ] || { [ -f "$TARGET" ] && is_ours "$TARGET"; }; then
    rm -f "$TARGET"; say "removed $TARGET"
  fi
  if [ -d "$PKG_TARGET" ] && is_our_pkg "$PKG_TARGET"; then
    rm -rf "$PKG_TARGET"; say "removed $PKG_TARGET"
  fi
  for name in claude-statusline claude-quest; do
    if [ -L "$BIN/$name" ]; then rm -f "$BIN/$name"; say "removed $BIN/$name"; fi
  done
  latest=""
  for f in $(ls -1t "$CLAUDE_DIR"/statusline.py.bak-* 2>/dev/null || true); do
    if ! is_ours "$f"; then latest="$f"; break; fi
  done
  if [ -n "$latest" ]; then
    mv "$latest" "$TARGET"; say "restored $(basename "$latest")"
  else
    say "no previous status line to restore"
  fi
  say "settings.json statusLine left as it is; point it elsewhere if you like"
  exit 0
fi

command -v python3 >/dev/null || { echo "python3 not found" >&2; exit 1; }
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)' \
  || { echo "claude-statusline needs Python 3.11 or newer" >&2; exit 1; }

echo "Installing claude-statusline from $REPO"
mkdir -p "$CLAUDE_DIR"

# --- 1. the entry point ---------------------------------------------------------
backup "$TARGET"
case "$MODE" in
  shim)
    # A shim, not a copy: CPython caches the engine's bytecode in the repo,
    # and a git pull updates the bar.
    cat > "$TARGET.tmp" <<SHIM
#!/usr/bin/env python3
"""$SHIM_MARK — edit the repo, not this file."""
import sys
sys.path.insert(0, "$REPO")
from claude_statusline.main import main
sys.exit(main())
SHIM
    chmod 0755 "$TARGET.tmp"; mv "$TARGET.tmp" "$TARGET"
    if [ -d "$PKG_TARGET" ] && is_our_pkg "$PKG_TARGET"; then
      rm -rf "$PKG_TARGET"; say "removed the old standalone copy $PKG_TARGET"
    fi
    say "wrote $TARGET -> $REPO"
    ;;
  symlink)
    rm -f "$TARGET"
    ln -sfn "$REPO/statusline.py" "$TARGET"
    say "symlinked $TARGET -> $REPO/statusline.py"
    ;;
  copy)
    rm -rf "$PKG_TARGET"
    cp -R "$REPO/claude_statusline" "$PKG_TARGET"
    find "$PKG_TARGET" -name __pycache__ -type d -prune -exec rm -rf {} +
    install -m 0755 "$REPO/statusline.py" "$TARGET"
    say "copied a standalone $TARGET + $(basename "$PKG_TARGET")/"
    ;;
esac
python3 -m compileall -q "$( [ "$MODE" = copy ] && echo "$PKG_TARGET" || echo "$REPO/claude_statusline" )" >/dev/null 2>&1 || true
link_bin claude-statusline

# --- 2. a config -----------------------------------------------------------------
if [ "$SEED_CONFIG" -eq 1 ] && [ ! -e "$CONFIG" ]; then
  mkdir -p "$CONFIG_DIR"
  # Pick a look this terminal can draw: Nerd Font icons and rounded chips
  # where the symbols exist, plain Unicode and square chips elsewhere.
  ICONS=unicode; STYLE=chips
  case "${TERM:-}:${TERM_PROGRAM:-}" in
    xterm-kitty:*|xterm-ghostty:*|*:WezTerm|*:ghostty) ICONS=nerd; STYLE=capsules ;;
  esac
  if [ "$ICONS" = unicode ] && command -v fc-list >/dev/null && fc-list 2>/dev/null | grep -qi "nerd font"; then
    ICONS=nerd; STYLE=capsules
  fi
  cat > "$CONFIG" <<CFG
# claude-statusline — your status line. Every key is optional.
#
#   statusline.py configure     change anything interactively, with a live preview
#   statusline.py themes        every theme drawn with your layout (also: styles, icons, bars)
#   statusline.py set <k> <v>   e.g. set theme nord, set style powerline, set quest.enabled true

preset = "classic"      # classic, compact, dashboard, focus, minimal, arcade
theme = "claude"        # claude, midnight, catppuccin, tokyo-night, nord, dracula, gruvbox, …
style = "$STYLE"     # minimal, classic, dots, chips, capsules, pills, powerline, slant
icons = "$ICONS"        # nerd, unicode, emoji, none
CFG
  say "created $CONFIG (style $STYLE, icons $ICONS)"
elif [ -e "$CONFIG" ]; then
  say "kept your $CONFIG"
fi

# --- 3. settings.json ------------------------------------------------------------
CLAUDE_SETTINGS="$SETTINGS" CLAUDE_STAMP="$STAMP" python3 - <<'PY'
import json, os, shutil, sys
path = os.environ["CLAUDE_SETTINGS"]
try:
    with open(path) as fh:
        cfg = json.load(fh)
except FileNotFoundError:
    cfg = {}
except Exception as exc:
    print(f"  settings.json is not valid JSON ({exc}); not touching it")
    print('  add this yourself:  "statusLine": {"type": "command", "command": '
          '"python3 -S ~/.claude/statusline.py", "padding": 0, "refreshInterval": 1}')
    sys.exit(0)
want = {"type": "command", "command": "python3 -S ~/.claude/statusline.py", "padding": 0, "refreshInterval": 1}
if cfg.get("statusLine") == want:
    print("  settings.json already points at the status line")
else:
    if os.path.exists(path):
        dest = f"{path}.bak-{os.environ['CLAUDE_STAMP']}"
        n = 1
        while os.path.exists(dest):
            dest = f"{path}.bak-{os.environ['CLAUDE_STAMP']}-{n}"
            n += 1
        shutil.copy2(path, dest)
        print(f"  backed up settings.json -> {os.path.basename(dest)}")
    cfg["statusLine"] = want
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(cfg, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    os.replace(tmp, path)
    print("  wrote statusLine into settings.json")
PY

# --- 4. Claude Quest -------------------------------------------------------------
if [ "$QUEST" -eq 1 ]; then
  echo
  echo "Claude Quest:"
  python3 -S "$TARGET" quest enable
fi

# --- 5. check --------------------------------------------------------------------
echo
if echo '{}' | python3 -S "$TARGET" >/dev/null 2>&1; then
  say "smoke test passed"
else
  echo "  smoke test FAILED" >&2; exit 1
fi
echo
python3 -S "$TARGET" doctor || true
echo
echo "Done. The bar appears on Claude Code's next refresh (or start a session)."
echo "Make it yours:   python3 $TARGET configure      (or: claude-statusline configure)"
[ "$QUEST" -eq 1 ] || echo "Play while you work:   python3 $TARGET quest enable"
