#!/usr/bin/env bash
# Install claude-statusline into ~/.claude and wire it into settings.json.
#
#   ./install.sh              install a shim + patch settings.json (fastest)
#   ./install.sh --symlink    symlink the script instead of using a shim
#   ./install.sh --copy       copy a standalone snapshot (portable, no repo)
#   ./install.sh --no-config  skip seeding the example config
#   ./install.sh --uninstall  restore the previous statusline
#
# Idempotent. Backs up anything it replaces to <file>.bak-<timestamp>.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
TARGET="$CLAUDE_DIR/statusline.py"
SETTINGS="$CLAUDE_DIR/settings.json"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/claude-statusline"
CONFIG="$CONFIG_DIR/config.toml"
STAMP="$(date +%Y%m%d-%H%M%S)"

MODE=shim
SEED_CONFIG=1
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --copy)      MODE=copy ;;
    --symlink)   MODE=symlink ;;
    --no-config) SEED_CONFIG=0 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help)   sed -n '2,10p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

say() { printf '  %s\n' "$*"; }

backup() {
  if [ -e "$1" ] && [ ! -L "$1" ]; then
    cp -p "$1" "$1.bak-$STAMP"
    say "backed up $(basename "$1") -> $(basename "$1").bak-$STAMP"
  fi
}

if [ "$UNINSTALL" -eq 1 ]; then
  echo "Uninstalling claude-statusline..."
  [ -L "$TARGET" ] && rm -f "$TARGET" && say "removed symlink $TARGET"
  if [ -f "$TARGET" ] && grep -q "claude-statusline/install.sh" "$TARGET" 2>/dev/null; then
    rm -f "$TARGET"; say "removed shim $TARGET"
  fi
  latest="$(ls -1t "$CLAUDE_DIR"/statusline.py.bak-* 2>/dev/null | head -1 || true)"
  if [ -n "$latest" ]; then
    mv "$latest" "$TARGET"; say "restored $latest"
  fi
  say "settings.json left untouched; edit statusLine.command if needed"
  exit 0
fi

command -v python3 >/dev/null || { echo "python3 not found" >&2; exit 1; }
python3 - <<'PY' || { echo "python 3.11+ required (tomllib)" >&2; exit 1; }
import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)
PY

echo "Installing claude-statusline from $REPO"
mkdir -p "$CLAUDE_DIR"

# --- 1. the script -----------------------------------------------------------
backup "$TARGET"
case "$MODE" in
  shim)
    # A shim lets CPython cache statusline.pyc in the repo's __pycache__.
    # Running the script directly recompiles ~1100 lines on every refresh,
    # which costs about 4 ms per second.
    cat > "$TARGET" <<SHIM
#!/usr/bin/env python3
"""Generated by claude-statusline/install.sh — edit the repo, not this file."""
import sys
sys.path.insert(0, "$REPO")
import statusline
sys.exit(statusline.main())
SHIM
    chmod 0755 "$TARGET"
    say "wrote shim $TARGET -> $REPO"
    python3 -c "import sys; sys.path.insert(0, '$REPO'); import statusline"  # warm .pyc
    say "warmed bytecode cache"
    ;;
  symlink)
    ln -sfn "$REPO/statusline.py" "$TARGET"
    say "symlinked $TARGET -> $REPO/statusline.py"
    ;;
  copy)
    install -m 0755 "$REPO/statusline.py" "$TARGET"
    say "copied standalone $TARGET"
    ;;
esac

# --- 2. the config -----------------------------------------------------------
if [ "$SEED_CONFIG" -eq 1 ] && [ ! -e "$CONFIG" ]; then
  mkdir -p "$CONFIG_DIR"
  cp "$REPO/statusline.example.toml" "$CONFIG"
  say "seeded $CONFIG"
elif [ -e "$CONFIG" ]; then
  say "kept existing $CONFIG"
fi

# --- 3. settings.json --------------------------------------------------------
backup "$SETTINGS"
CLAUDE_SETTINGS="$SETTINGS" python3 - <<'PY'
import json, os, sys
path = os.environ["CLAUDE_SETTINGS"]
try:
    with open(path) as fh:
        cfg = json.load(fh)
except FileNotFoundError:
    cfg = {}
except Exception as exc:
    print(f"  settings.json is not valid JSON ({exc}); not touching it")
    print(f"  add this yourself:  \"statusLine\": {{\"type\": \"command\", "
          f"\"command\": \"python3 ~/.claude/statusline.py\"}}")
    sys.exit(0)

want = {"type": "command", "command": "python3 ~/.claude/statusline.py",
        "padding": 0, "refreshInterval": 1}
if cfg.get("statusLine") == want:
    print("  settings.json already correct")
else:
    cfg["statusLine"] = want
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(cfg, fh, indent=2)
        fh.write("\n")
    os.replace(tmp, path)
    print("  wrote statusLine into settings.json")
PY

# --- 4. verify ---------------------------------------------------------------
echo
if echo '{}' | python3 "$TARGET" >/dev/null 2>&1; then
  say "smoke test passed"
else
  echo "  smoke test FAILED" >&2; exit 1
fi
echo
python3 "$TARGET" --doctor
echo
echo "Done. Start a new Claude Code session, or run /statusline to reload."
echo "Preview:   python3 $TARGET --demo"
echo "Calibrate: python3 $TARGET --ruler   (see README)"
