"""Switching Claude Quest on and off.

    enable    hooks into ~/.claude/settings.json, the /quest command, a
              `claude-quest` command on your PATH, and [quest] enabled = true
    disable   all of that removed again; the save is kept
    status    what is on, and where everything lives

Hooks that earlier, standalone Claude Quest installs registered are replaced
on enable and removed on disable, so exactly one copy of the game runs.
"""
from __future__ import annotations

import os

from .. import settings as st
from . import home, state_path

COMMANDS = os.path.join(st.CLAUDE_DIR, "commands")
COMMAND_FILE = os.path.join(COMMANDS, "quest.md")
BIN = os.path.expanduser("~/.local/bin")
MARK = "<!-- claude-statusline: quest command -->"

COMMAND_TEXT = """---
description: Claude Quest — your hero, bag, quests, shop, boss and pet (try /quest help)
argument-hint: "[sheet|bag|inspect|equip|use|sell|forge|shop|buy|quests|boss|pet|titles|log|guide|help] [args]"
allowed-tools: Bash(python3 -S ~/.claude/statusline.py quest:*)
---
{mark}
!`python3 -S ~/.claude/statusline.py quest $ARGUMENTS`

Show the output above to the user exactly as printed, in a code block, with no commentary.
"""


def _ours(path) -> bool:
    try:
        with open(path) as fh:
            return MARK in fh.read()
    except OSError:
        return False


def _legacy_command(path) -> bool:
    try:
        with open(path) as fh:
            text = fh.read()
        return "claude-quest $ARGUMENTS" in text or "Claude Quest" in text
    except OSError:
        return False


FORWARDER = """#!/usr/bin/env python3
\"\"\"Generated by claude-statusline: a Claude Code session started before Claude Quest moved
into claude-statusline still calls this file from its hooks; it runs the new game. Safe to
delete once every Claude Code session has been restarted.\"\"\"
import sys
sys.path.insert(0, {root!r})
from claude_statusline.quest.main import main
sys.exit(main())
"""


def forward_legacy_shim(log=print):
    """Point an older, standalone Claude Quest's entry script at this engine.

    Claude Code keeps the hooks a session started with, so sessions already
    running call the old script until they restart. Rewriting it keeps them
    playing the same game (this one) instead of failing or running old code.
    """
    legacy = os.path.join(home(), "quest.py")
    if not os.path.exists(legacy):
        return
    try:
        with open(legacy) as fh:
            text = fh.read()
    except OSError:
        return
    if "Generated by claude-quest/install.sh" not in text and "claude_quest" not in text:
        return
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    tmp = legacy + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(FORWARDER.format(root=root))
    os.chmod(tmp, 0o755)
    os.replace(tmp, legacy)
    log(f"  running sessions: {legacy} now runs this engine's game until they restart")


def set_config_enabled(on: bool) -> str:
    from ..config import write_path
    from ..tomlw import set_key
    path = write_path()
    try:
        with open(path) as fh:
            text = fh.read()
    except FileNotFoundError:
        text = ""
    new = set_key(text, "quest.enabled", bool(on))
    if new != text:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = f"{path}.{os.getpid()}.tmp"
        with open(tmp, "w") as fh:
            fh.write(new if new.endswith("\n") else new + "\n")
        os.replace(tmp, path)
    return path


def enable(log=print) -> int:
    if not os.path.exists(st.ENTRY):
        log(f"  note: {st.ENTRY} is missing; run install.sh first so the hooks have something to call")
    try:
        data = st.load()
    except st.SettingsError as exc:
        log(f"  {exc}")
        return 1
    before = st.strip_quest_hooks(data)
    st.add_quest_hooks(data)
    backup = st.save(data)
    log(f"  hooks: {len(st.HOOK_EVENTS)} registered in {st.SETTINGS}"
        + (f" (replaced {before} older)" if before else "") + (f"; backup {os.path.basename(backup)}" if backup else ""))
    os.makedirs(COMMANDS, exist_ok=True)
    if os.path.exists(COMMAND_FILE) and not _ours(COMMAND_FILE) and not _legacy_command(COMMAND_FILE):
        log(f"  kept your own {COMMAND_FILE}; /quest is not installed")
    else:
        with open(COMMAND_FILE, "w") as fh:
            fh.write(COMMAND_TEXT.format(mark=MARK))
        log(f"  /quest: {COMMAND_FILE}")
    link = os.path.join(BIN, "claude-quest")
    try:
        os.makedirs(BIN, exist_ok=True)
        if os.path.islink(link) or not os.path.exists(link):
            if os.path.lexists(link):
                os.unlink(link)
            os.symlink(st.ENTRY, link)
            log(f"  command: {link}")
    except OSError as exc:
        log(f"  could not link {link}: {exc}")
    forward_legacy_shim(log)
    path = set_config_enabled(True)
    log(f"  config: [quest] enabled = true in {path}")
    log(f"  save: {state_path()}" + ("" if os.path.exists(state_path()) else " (starts on your next prompt)"))
    return 0


def disable(log=print) -> int:
    try:
        data = st.load()
    except st.SettingsError as exc:
        log(f"  {exc}")
        return 1
    removed = st.strip_quest_hooks(data)
    if removed:
        backup = st.save(data)
        log(f"  hooks: removed {removed} from {st.SETTINGS}" + (f"; backup {os.path.basename(backup)}" if backup else ""))
    else:
        log("  hooks: none registered")
    if os.path.exists(COMMAND_FILE) and (_ours(COMMAND_FILE) or _legacy_command(COMMAND_FILE)):
        os.unlink(COMMAND_FILE)
        log(f"  /quest: removed {COMMAND_FILE}")
    link = os.path.join(BIN, "claude-quest")
    if os.path.islink(link):
        os.unlink(link)
        log(f"  command: removed {link}")
    path = set_config_enabled(False)
    log(f"  config: [quest] enabled = false in {path}")
    log(f"  your save is kept: {state_path()}")
    return 0


def status(log=print) -> int:
    from ..config import compiled
    on = bool(compiled()["quest"].get("enabled"))
    try:
        hooks = st.quest_hooks_present(st.load())
    except st.SettingsError:
        hooks = False
    log(f"  Claude Quest   {'on' if on else 'off'}" + ("" if on == hooks else
                                                        f"  (hooks {'present' if hooks else 'missing'}: run "
                                                        f"`statusline.py quest {'enable' if on else 'disable'}`)"))
    log(f"  hooks          {'registered' if hooks else 'not registered'} in {st.SETTINGS}")
    log(f"  /quest         {'installed' if os.path.exists(COMMAND_FILE) else 'not installed'}")
    log(f"  save           {state_path() if os.path.exists(state_path()) else '(none yet)'}")
    if os.path.exists(state_path()):
        from .state import load_readonly
        from . import view
        v = view.build(load_readonly())
        log(f"  hero           Lv {v['level']} {v['title']}, {v['xp_in']}/{v['xp_need']} XP, {v['gold']} gold, "
            f"{v['bag']} items")
    log(f"  home           {home()}")
    return 0


def command(cmd, args=(), log=print) -> int:
    return {"enable": enable, "disable": disable, "status": status}[cmd](log)
